In [4]:
import numpy as np
import random

In [5]:
np.random.random(1)

array([0.30559801])

In [6]:
np.random.random((4,3))

array([[0.62207545, 0.93058452, 0.82816348],
       [0.36038571, 0.23367322, 0.95007752],
       [0.73248932, 0.53986965, 0.61720571],
       [0.97809364, 0.60409978, 0.42753363]])

In [11]:
np.random.randint(1,4, (2,4,2))

array([[[1, 2],
        [2, 2],
        [1, 3],
        [3, 1]],

       [[3, 2],
        [3, 1],
        [3, 1],
        [1, 1]]])

In [ ]:
np.random.randint(1,4)