# Library Import

In [2]:
import numpy as np

# Numpy ones matrix

In [3]:
arr_ones = np.ones(4)
arr_ones

array([1., 1., 1., 1.])

In [4]:
arr_ones.dtype

dtype('float64')

In [6]:
arr_ones = np.ones((3,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
arr_ones = np.ones((3,4),dtype = int)
arr_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# Numpy zero matrix

In [11]:
arr_zero = np.zeros((4,5))
arr_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
arr_zero = np.zeros((4,5), dtype = bool)
arr_zero

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [13]:
arr_zero = np.zeros((4,5), dtype = str)
arr_zero

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')