In [2]:
import numpy as np

# arrange() / reshape()

In [13]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(12,21).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[12 13 14]
 [15 16 17]
 [18 19 20]]


# Matrix addition

In [14]:
arr1 + arr2

array([[13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [15]:
np.add(arr1,arr2)

array([[13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

# Matrix Subtraction

In [16]:
arr1 - arr2

array([[-11, -11, -11],
       [-11, -11, -11],
       [-11, -11, -11]])

In [17]:
arr2 - arr1

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [18]:
np.subtract(arr1,arr2)

array([[-11, -11, -11],
       [-11, -11, -11],
       [-11, -11, -11]])

In [19]:
np.subtract(arr2,arr1)

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

# Matrix Multiplication

In [21]:
arr1 / arr2

array([[0.08333333, 0.15384615, 0.21428571],
       [0.26666667, 0.3125    , 0.35294118],
       [0.38888889, 0.42105263, 0.45      ]])

In [25]:
arr2/arr1

array([[12.        ,  6.5       ,  4.66666667],
       [ 3.75      ,  3.2       ,  2.83333333],
       [ 2.57142857,  2.375     ,  2.22222222]])

In [23]:
np.divide(arr1,arr2)

array([[0.08333333, 0.15384615, 0.21428571],
       [0.26666667, 0.3125    , 0.35294118],
       [0.38888889, 0.42105263, 0.45      ]])

In [24]:
np.divide(arr2,arr1)

array([[12.        ,  6.5       ,  4.66666667],
       [ 3.75      ,  3.2       ,  2.83333333],
       [ 2.57142857,  2.375     ,  2.22222222]])

# Matrix Mutliplication

In [27]:
np.multiply(arr1,arr2)

array([[ 12,  26,  42],
       [ 60,  80, 102],
       [126, 152, 180]])

In [28]:
arr1 * arr2

array([[ 12,  26,  42],
       [ 60,  80, 102],
       [126, 152, 180]])

In [29]:
arr1 @ arr2

array([[ 96, 102, 108],
       [231, 246, 261],
       [366, 390, 414]])

In [30]:
arr1.dot(arr2)

array([[ 96, 102, 108],
       [231, 246, 261],
       [366, 390, 414]])

In [31]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

# Matrix Min/Max

In [33]:
arr2.max()

20

In [34]:
arr2.argmax()

8

In [35]:
arr2.max(axis = 0)

array([18, 19, 20])

In [36]:
arr2.max(axis = 1)

array([14, 17, 20])

In [37]:
arr2.min()

12

In [38]:
arr2.argmin()

0

In [39]:
arr2.min(axis = 1)

array([12, 15, 18])

In [40]:
arr2.min(axis = 0)

array([12, 13, 14])

# Matrix Sum

In [41]:
np.sum(arr2)

144

In [42]:
np.sum(arr2, axis = 0)

array([45, 48, 51])

In [43]:
np.sum(arr2, axis = 1)

array([39, 48, 57])

# Log, SquareRot, Exponent, Standord Diviasion