# Numpy Arr Split

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,17).reshape(4,4)
arr2 = np.arange(17,33).reshape(4,4)
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [5]:
np.split(arr1,2)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [9]:
list = np.split(arr1,4)

In [10]:
type(list)

list

In [11]:
list[0]

array([[1, 2, 3, 4]])

In [12]:
type(list[0])

numpy.ndarray